# ============================================================================
# LifeOS Agent Packet Templates v1.0
# ============================================================================
# Ready-to-use templates. Copy and fill in values.
# Delete comments before use. Required fields marked [REQUIRED].
# ============================================================================

---
# TEMPLATE 1: COUNCIL_REVIEW_PACKET
---
packet_id: ""                    # [REQUIRED] UUID v4
packet_type: "COUNCIL_REVIEW"
schema_version: "1.0.0"
created_at: ""                   # [REQUIRED] ISO 8601
source_agent: ""                 # [REQUIRED]
target_agent: ""                 # [REQUIRED] council-{role}
chain_id: ""                     # [REQUIRED] UUID v4
parent_packet_id: null           # Optional
priority: "P2_NORMAL"            # P0_CRITICAL | P1_HIGH | P2_NORMAL | P3_LOW
ttl_hours: 48
tags: []

review_request:
  review_type: ""                # [REQUIRED] CODE | ARCHITECTURE | GOVERNANCE | SECURITY | DOCUMENTATION
  subject_ref: ""                # [REQUIRED] What's being reviewed
  subject_summary: ""            # [REQUIRED] 1-3 sentences
  urgency_rationale: ""
  deadline: ""                   # ISO 8601

role_context:
  role_id: ""                    # [REQUIRED]
  role_prompt: ""                # [REQUIRED] Full role definition
  decision_authority:            # [REQUIRED]
    - ""
  escalation_triggers:           # [REQUIRED]
    - ""

background:
  prior_decisions:
    - decision_id: ""
      summary: ""
      relevance: ""
  related_docs:                  # [REQUIRED] At least one
    - doc_ref: ""
      doc_type: ""               # SPEC | GOVERNANCE | CODE | TEST
      relevance: ""
  context_summary: ""            # [REQUIRED]

criteria:
  must_pass:                     # [REQUIRED] At least one
    - criterion_id: ""
      description: ""
      verification_method: ""
  should_pass:
    - criterion_id: ""
      description: ""
      verification_method: ""
  out_of_scope: []

output_format:
  ruling_structure:
    outcome: "APPROVED | APPROVED_WITH_CONDITIONS | REJECTED | ESCALATED | DEFERRED | ABSTAINED"
    confidence: "HIGH | MEDIUM | LOW"
    findings: "list"
    conditions: "list if APPROVED_WITH_CONDITIONS"
    rationale: "required"
  fix_structure:
    severity: "P0_BLOCKER | P1_CRITICAL | P2_MAJOR | P3_MINOR | P4_TRIVIAL"
    location: "file:line"
    issue: "description"
    suggested_fix: "remediation"
    verification: "confirmation method"

---
# TEMPLATE 2: COUNCIL_APPROVAL_PACKET
---
packet_id: ""
packet_type: "COUNCIL_APPROVAL"
schema_version: "1.0.0"
created_at: ""
source_agent: "council-aggregator"
target_agent: ""
chain_id: ""
parent_packet_id: ""
priority: "P2_NORMAL"
tags: []

aggregation:
  subject_ref: ""                # [REQUIRED]
  quorum_required: 0             # [REQUIRED]
  quorum_achieved: 0             # [REQUIRED]
  voting_rule: ""                # [REQUIRED] UNANIMOUS | MAJORITY | WEIGHTED

member_rulings:                  # [REQUIRED]
  - member_role_id: ""
    review_packet_id: ""
    outcome: ""
    confidence: ""
    blocking_findings: 0
    non_blocking_findings: 0

consolidated:
  outcome: ""                    # [REQUIRED]
  outcome_rationale: ""          # [REQUIRED]
  blocking_issues:               # [REQUIRED if REJECTED]
    - finding_id: ""
      source_member: ""
      severity: ""
      issue: ""
      suggested_fix: ""
  conditions:                    # [REQUIRED if APPROVED_WITH_CONDITIONS]
    - condition_id: ""
      description: ""
      deadline: ""
      verification: ""
  dissents:
    - member_role_id: ""
      dissent_rationale: ""

---
# TEMPLATE 3: GATE_APPROVAL_PACKET
---
packet_id: ""
packet_type: "GATE_APPROVAL"
schema_version: "1.0.0"
created_at: ""
source_agent: "gate-controller"
target_agent: ""
chain_id: ""
parent_packet_id: ""
priority: "P1_HIGH"
tags: []

gate:
  gate_id: ""                    # [REQUIRED]
  gate_type: ""                  # [REQUIRED] TIER_PROMOTION | DEPLOY | RELEASE | MERGE
  tier_from: ""
  tier_to: ""

prerequisites:
  required_approvals:            # [REQUIRED]
    - approval_type: ""          # COUNCIL | HUMAN | AUTOMATED
      approval_ref: ""
      status: ""                 # MET | NOT_MET | WAIVED
      waiver_rationale: ""       # Required if WAIVED
  required_artifacts:            # [REQUIRED]
    - artifact_type: ""
      artifact_ref: ""
      status: ""                 # PRESENT | MISSING | INVALID
  required_tests:                # [REQUIRED]
    - test_suite: ""
      pass_count: 0
      fail_count: 0
      skip_count: 0
      status: ""                 # PASSED | FAILED | NOT_RUN

decision:
  outcome: ""                    # [REQUIRED] APPROVED | REJECTED | ESCALATED
  decided_by: ""                 # [REQUIRED]
  decided_at: ""                 # [REQUIRED]
  rationale: ""                  # [REQUIRED]
  unmet_prerequisites:           # Required if REJECTED
    - prerequisite_ref: ""
      gap_description: ""
  next_gate: ""

---
# TEMPLATE 4: BUILD_PACKET
---
packet_id: ""
packet_type: "BUILD"
schema_version: "1.0.0"
created_at: ""
source_agent: ""
target_agent: "builder"
chain_id: ""
parent_packet_id: ""
priority: "P2_NORMAL"
tags: []

scope:
  component: ""                  # [REQUIRED]
  build_type: ""                 # [REQUIRED] NEW | MODIFY | REFACTOR | FIX
  tier: ""                       # [REQUIRED]

tdd_spec:
  acceptance_tests:              # [REQUIRED]
    - test_id: ""
      description: ""
      preconditions: []
      input: ""
      expected_output: ""
      verification_command: ""
  test_file_paths: []            # [REQUIRED]
  coverage_requirement: ""

functional_spec:
  purpose: ""                    # [REQUIRED]
  inputs:                        # [REQUIRED]
    - name: ""
      type: ""
      constraints: ""
      required: true
  outputs:                       # [REQUIRED]
    - name: ""
      type: ""
      guarantees: ""
  behavior:                      # [REQUIRED]
    - behavior_id: ""
      description: ""
      edge_cases: []
  error_handling:                # [REQUIRED]
    - error_type: ""
      handling: ""

constraints:
  must_not: []                   # [REQUIRED]
  must_use: []
  file_allowlist: []             # [REQUIRED]
  dependencies: []

context:
  related_code:
    - file_path: ""
      relevance: ""
      snippet: ""
  design_decisions:
    - decision_ref: ""
      summary: ""

---
# TEMPLATE 5: REVIEW_PACKET
---
packet_id: ""
packet_type: "REVIEW"
schema_version: "1.0.0"
created_at: ""
source_agent: "builder"
target_agent: "reviewer"
chain_id: ""
parent_packet_id: ""
priority: "P2_NORMAL"
tags: []

review_meta:
  mission: ""                    # [REQUIRED]
  build_packet_id: ""            # [REQUIRED]
  status: ""                     # [REQUIRED] COMPLETE | PARTIAL | BLOCKED
  summary: ""                    # [REQUIRED]

implementation:
  fixes_implemented:             # [REQUIRED]
    - fix_id: ""
      severity: ""
      issue: ""
      fix_description: ""
      verification: ""
      status: ""                 # FIXED | PARTIAL | WONT_FIX
  contracts:
    - contract_name: ""
      description: ""
      rules: []
      fail_cases:
        - pattern: ""
          error_reason: ""

test_results:
  suite_name: ""                 # [REQUIRED]
  total: 0                       # [REQUIRED]
  passed: 0                      # [REQUIRED]
  failed: 0                      # [REQUIRED]
  skipped: 0
  test_details:                  # [REQUIRED]
    - test_id: ""
      status: ""                 # PASSED | FAILED | SKIPPED
      failure_reason: ""         # Required if FAILED

file_manifest:
  files:                         # [REQUIRED]
    - path: ""
      lines: 0
      change_type: ""            # CREATED | MODIFIED | DELETED
      change_summary: ""
  total_lines_changed: 0         # [REQUIRED]

code_appendix:
  - function_name: ""
    purpose: ""
    code: |
      # code here
    notes: []

---
# TEMPLATE 6: FIX_PACKET
---
packet_id: ""
packet_type: "FIX"
schema_version: "1.0.0"
created_at: ""
source_agent: ""
target_agent: "builder"
chain_id: ""
parent_packet_id: ""
priority: "P1_HIGH"
tags: []

source:
  source_packet_id: ""           # [REQUIRED]
  source_type: ""                # [REQUIRED] REVIEW | COUNCIL | HUMAN

fixes:                           # [REQUIRED] At least one
  - fix_id: ""
    severity: ""                 # P0_BLOCKER | P1_CRITICAL | P2_MAJOR | P3_MINOR | P4_TRIVIAL
    location:
      file: ""
      line_start: 0
      line_end: 0
      function: ""
    issue:
      description: ""            # [REQUIRED]
      evidence: ""
    remediation:
      approach: ""               # [REQUIRED]
      code_suggestion: ""
      alternatives: []
    verification:
      method: ""                 # [REQUIRED]
      test_ids: []

pass_criteria:
  all_fixes_required: true       # [REQUIRED]
  verification_command: ""       # [REQUIRED]
  expected_outcome: ""           # [REQUIRED]

constraints:
  file_allowlist: []             # [REQUIRED]
  time_budget_hours: null
  escalate_if: []                # [REQUIRED]

---
# TEMPLATE 7: ESCALATION_PACKET
---
packet_id: ""
packet_type: "ESCALATION"
schema_version: "1.0.0"
created_at: ""
source_agent: ""
target_agent: ""                 # Human or higher-tier agent
chain_id: ""
parent_packet_id: ""
priority: "P1_HIGH"
tags: []

context:
  escalating_agent: ""           # [REQUIRED]
  original_task_ref: ""          # [REQUIRED]
  escalation_reason: ""          # [REQUIRED] AUTHORITY_EXCEEDED | AMBIGUOUS_SPEC | 
                                 #   CONFLICTING_REQUIREMENTS | SAFETY_CONCERN | 
                                 #   RESOURCE_EXCEEDED | UNKNOWN_FAILURE
  urgency: ""                    # [REQUIRED] BLOCKING | HIGH | NORMAL

decision_needed:
  question: ""                   # [REQUIRED]
  options:                       # [REQUIRED]
    - option_id: ""
      description: ""
      pros: []
      cons: []
      agent_recommendation: ""
  constraints: []                # [REQUIRED]

supporting_info:
  attempted_actions:             # [REQUIRED]
    - action: ""
      outcome: ""
      why_insufficient: ""
  relevant_docs: []
  state_snapshot: ""

response_format:
  decision_options: []           # [REQUIRED]
  additional_info_request: false
  timeout_action: ""             # [REQUIRED]

---
# TEMPLATE 8: HANDOFF_PACKET
---
packet_id: ""
packet_type: "HANDOFF"
schema_version: "1.0.0"
created_at: ""
source_agent: ""
target_agent: ""
chain_id: ""
parent_packet_id: ""
priority: "P2_NORMAL"
tags: []

handoff:
  reason: ""                     # [REQUIRED] TASK_COMPLETE | SPECIALIZATION_NEEDED |
                                 #   RESOURCE_LIMIT | SCHEDULED_ROTATION | ERROR_RECOVERY
  handoff_point: ""              # [REQUIRED]

task_state:
  original_task_ref: ""          # [REQUIRED]
  task_description: ""           # [REQUIRED]
  progress_summary: ""           # [REQUIRED]
  completion_percentage: 0       # [REQUIRED]
  current_phase: ""              # [REQUIRED]

work_products:
  files_created: []              # [REQUIRED]
  files_modified: []             # [REQUIRED]
  artifacts_produced:
    - artifact_type: ""
      artifact_ref: ""
  decisions_made:                # [REQUIRED]
    - decision: ""
      rationale: ""
      reversible: true

continuation:
  next_steps: []                 # [REQUIRED]
  blockers: []                   # [REQUIRED]
  warnings: []
  context_refs: []

---
# TEMPLATE 9: CHECKPOINT_PACKET
---
packet_id: ""
packet_type: "CHECKPOINT"
schema_version: "1.0.0"
created_at: ""
source_agent: ""
target_agent: "orchestrator"
chain_id: ""
parent_packet_id: ""
priority: "P3_LOW"
tags: []

checkpoint:
  checkpoint_number: 0           # [REQUIRED]
  checkpoint_type: ""            # [REQUIRED] SCHEDULED | MILESTONE | ON_DEMAND | PRE_RISKY_ACTION
  task_ref: ""                   # [REQUIRED]

progress:
  started_at: ""                 # [REQUIRED]
  checkpoint_at: ""              # [REQUIRED]
  elapsed_hours: 0               # [REQUIRED]
  completion_percentage: 0       # [REQUIRED]
  phase: ""                      # [REQUIRED]

status:
  health: ""                     # [REQUIRED] GREEN | YELLOW | RED
  summary: ""                    # [REQUIRED]
  accomplishments: []            # [REQUIRED]
  current_activity: ""           # [REQUIRED]
  next_planned: []               # [REQUIRED]

metrics:
  tests_passing: 0
  tests_failing: 0
  files_modified: 0
  lines_changed: 0
  errors_encountered: 0
  errors_recovered: 0
  custom_metrics: {}

flags:
  needs_attention: false         # [REQUIRED]
  attention_reason: ""           # Required if needs_attention
  decision_pending: false        # [REQUIRED]
  blocked: false                 # [REQUIRED]
  blocker_description: ""        # Required if blocked

---
# TEMPLATE 10: ROLLBACK_PACKET
---
packet_id: ""
packet_type: "ROLLBACK"
schema_version: "1.0.0"
created_at: ""
source_agent: ""
target_agent: "executor"
chain_id: ""
parent_packet_id: ""
priority: "P0_CRITICAL"
tags: []

trigger:
  trigger_type: ""               # [REQUIRED] GOVERNANCE_VIOLATION | TEST_FAILURE | 
                                 #   HUMAN_OVERRIDE | SAFETY_LIMIT | AUTOMATIC_THRESHOLD
  trigger_source: ""             # [REQUIRED]
  trigger_evidence: ""           # [REQUIRED]
  severity: ""                   # [REQUIRED] CRITICAL | HIGH | NORMAL

scope:
  rollback_type: ""              # [REQUIRED] FULL | PARTIAL | SELECTIVE
  target_ref: ""                 # [REQUIRED]
  rollback_to: ""                # [REQUIRED] Commit SHA, checkpoint, etc.
  affected_components: []        # [REQUIRED]

execution:
  steps:                         # [REQUIRED]
    - step_number: 0
      action: ""
      verification: ""
      rollback_if_failed: ""
  preserve: []
  notify: []                     # [REQUIRED]

post_rollback:
  verification_command: ""       # [REQUIRED]
  expected_state: ""             # [REQUIRED]
  follow_up_required:
    - action: ""
      owner: ""
      deadline: ""

---
# TEMPLATE 11: TASK_DECOMPOSITION_PACKET
---
packet_id: ""
packet_type: "TASK_DECOMPOSITION"
schema_version: "1.0.0"
created_at: ""
source_agent: "orchestrator"
target_agent: ""
chain_id: ""
parent_packet_id: ""
priority: "P2_NORMAL"
tags: []

intent:
  source: ""                     # [REQUIRED]
  raw_intent: ""                 # [REQUIRED]
  interpreted_goal: ""           # [REQUIRED]
  success_criteria: []           # [REQUIRED]

subtasks:                        # [REQUIRED]
  - subtask_id: ""
    description: ""
    task_type: ""                # BUILD | REVIEW | TEST | DOCUMENT | DEPLOY
    assigned_agent: ""
    dependencies: []             # [REQUIRED]
    estimated_hours: null
    inputs: []                   # [REQUIRED]
    outputs: []                  # [REQUIRED]
    acceptance_criteria: []      # [REQUIRED]

execution_plan:
  parallelization: ""            # [REQUIRED] SEQUENTIAL | PARALLEL | MIXED
  critical_path: []              # [REQUIRED]
  total_estimated_hours: null
  checkpoints:                   # [REQUIRED]
    - after_subtask: ""
      checkpoint_type: ""

constraints:
  time_budget_hours: null
  tier_limit: ""                 # [REQUIRED]
  human_approval_required: []    # [REQUIRED]
  escalation_triggers: []        # [REQUIRED]

---
# TEMPLATE 12: SPEC_PACKET
---
packet_id: ""
packet_type: "SPEC"
schema_version: "1.0.0"
created_at: ""
source_agent: ""
target_agent: ""
chain_id: ""
parent_packet_id: ""
priority: "P2_NORMAL"
tags: []

spec_meta:
  spec_type: ""                  # [REQUIRED] FEATURE | COMPONENT | INTEGRATION | PROCESS | POLICY
  spec_status: ""                # [REQUIRED] DRAFT | REVIEW | APPROVED | SUPERSEDED
  version: ""                    # [REQUIRED] Semver
  supersedes: ""

problem:
  description: ""                # [REQUIRED]
  impact: ""                     # [REQUIRED]
  current_state: ""
  constraints: []                # [REQUIRED]

solution:
  summary: ""                    # [REQUIRED]
  approach: ""                   # [REQUIRED]
  components:                    # [REQUIRED]
    - component_name: ""
      responsibility: ""
      interfaces: []
  data_flow: ""

alternatives:                    # [REQUIRED] At least one
  - alternative_id: ""
    description: ""
    pros: []
    cons: []
    rejection_reason: ""

implementation:
  suggested_approach: ""         # [REQUIRED]
  estimated_effort: ""           # [REQUIRED]
  risks:                         # [REQUIRED]
    - risk: ""
      likelihood: ""             # HIGH | MEDIUM | LOW
      impact: ""                 # HIGH | MEDIUM | LOW
      mitigation: ""
  dependencies: []               # [REQUIRED]

acceptance:
  criteria:                      # [REQUIRED]
    - criterion_id: ""
      description: ""
      verification: ""
  out_of_scope: []               # [REQUIRED]

---
# TEMPLATE 13: DOCUMENT_JOURNEY_TRACKER
---
packet_id: ""
packet_type: "JOURNEY_TRACKER"
schema_version: "1.0.0"
created_at: ""
source_agent: "orchestrator"
target_agent: "all"
chain_id: ""                     # Same as journey_id
parent_packet_id: null
priority: "P3_LOW"
tags: []

journey:
  journey_id: ""                 # [REQUIRED] Same as chain_id
  journey_type: ""               # [REQUIRED] FEATURE | FIX | GOVERNANCE | DOCUMENTATION
  title: ""                      # [REQUIRED]
  initiated_by: ""               # [REQUIRED]
  initiated_at: ""               # [REQUIRED]

current_state:
  status: ""                     # [REQUIRED] IN_PROGRESS | BLOCKED | COMPLETE | ABANDONED
  phase: ""                      # [REQUIRED]
  active_packet_id: ""           # [REQUIRED]
  active_agent: ""               # [REQUIRED]
  last_updated: ""               # [REQUIRED]

history:                         # [REQUIRED]
  - sequence: 0
    packet_id: ""
    packet_type: ""
    agent: ""
    started_at: ""
    completed_at: ""
    outcome: ""
    summary: ""

milestones:                      # [REQUIRED]
  - milestone_id: ""
    description: ""
    status: ""                   # PENDING | REACHED | SKIPPED
    reached_at: ""
    packet_id: ""

blockers:                        # [REQUIRED] (can be empty list)
  - blocker_id: ""
    description: ""
    since: ""
    blocking_packet_id: ""
    resolution_path: ""

flags:
  needs_human_attention: false
  attention_reason: ""
  stale: false
  stale_since: ""

metrics:
  total_packets: 0
  elapsed_hours: 0
  times_escalated: 0
  times_blocked: 0
  rework_cycles: 0
